M48
; DRILL file {KiCad 8.99.0-3402-gadd58faa30} date 2024-12-15T16:52:06-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-15T16:52:06-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.99.0-3402-gadd58faa30
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.313Y-3.0238
T2
X6.5847Y-1.6675
X7.3406Y-3.1635
M30
